#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
evaluate_csnp_3var_cpdag_and_merge.py

Evaluate a CSNP/CausalStructureNeuralProcess model on the 3-variable benchmark
files generated by generate_benchmark_3var.py, using the same CPDAG metrics as
our AVICI/PC/GES benchmark script.

Typical usage, in the csnp conda environment:

  cd /home/rtyen/projects/CausalStructureNeuralProcess-main
  python evaluate_csnp_3var_cpdag_and_merge.py \
    --csnp_work_dir /home/rtyen/projects/CausalStructureNeuralProcess-main/ml2_meta_causal_discovery \
    --benchmark_root /home/rtyen/projects/avici-main/benchmark_data \
    --results_dir /home/rtyen/projects/avici-main/benchmark_results_3var_cpdag

Outputs by default:
  - csnp_raw_results_cpdag.csv
  - raw_results_cpdag_with_csnp.csv
  - summary_results_cpdag_with_csnp.csv

It does NOT overwrite the old AVICI/PC/GES raw_results_cpdag.csv unless you pass
--replace_original.
"""

from __future__ import annotations

import argparse
import glob
import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple

import h5py
import numpy as np
import pandas as pd
import torch as th

from ml2_meta_causal_discovery.models.causaltransformernp import (
    CausalProbabilisticARDecoder,
    CausalProbabilisticDecoder,
)


# =============================================================================
# Constants
# =============================================================================

EDGE_ORDER_3VAR: List[Tuple[int, int]] = [
    (0, 1),
    (0, 2),
    (1, 0),
    (1, 2),
    (2, 0),
    (2, 1),
]

PAIR_ORDER_3VAR: List[Tuple[int, int]] = [
    (0, 1),
    (0, 2),
    (1, 2),
]


# =============================================================================
# Basic utilities
# =============================================================================

def parse_int_list(s: str) -> List[int]:
    return [int(x.strip()) for x in str(s).split(",") if x.strip()]


def remove_diag(g: np.ndarray) -> np.ndarray:
    out = np.asarray(g).copy()
    np.fill_diagonal(out, 0)
    return out


def maybe_standardize(x: np.ndarray, standardize: bool = True) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64)
    if not standardize:
        return x
    return (x - x.mean(axis=0, keepdims=True)) / (x.std(axis=0, keepdims=True) + 1e-8)


def is_acyclic(adj: np.ndarray) -> bool:
    adj = remove_diag(adj).astype(int)
    d = adj.shape[0]
    indeg = adj.sum(axis=0).astype(int)
    queue = [i for i in range(d) if indeg[i] == 0]
    visited = 0
    while queue:
        u = queue.pop(0)
        visited += 1
        for v in np.where(adj[u] == 1)[0]:
            indeg[v] -= 1
            if indeg[v] == 0:
                queue.append(int(v))
    return visited == d


def skeleton_from_dag_or_directed(g: np.ndarray) -> np.ndarray:
    g = remove_diag(g).astype(int)
    skel = ((g + g.T) > 0).astype(int)
    np.fill_diagonal(skel, 0)
    return skel


def skeleton_from_cpdag(directed: np.ndarray, undirected: np.ndarray) -> np.ndarray:
    directed = remove_diag(directed).astype(int)
    undirected = remove_diag(undirected).astype(int)
    skel = ((directed + directed.T + undirected + undirected.T) > 0).astype(int)
    np.fill_diagonal(skel, 0)
    return skel


def matrix_to_directed_edges(g: np.ndarray) -> str:
    g = remove_diag(g).astype(int)
    d = g.shape[0]
    edges: List[str] = []
    for i in range(d):
        for j in range(d):
            if i != j and g[i, j] == 1:
                edges.append(f"{i}->{j}")
    return ", ".join(edges) if edges else "(none)"


def matrix_to_undirected_edges(u: np.ndarray) -> str:
    u = remove_diag(u).astype(int)
    d = u.shape[0]
    edges: List[str] = []
    for i in range(d):
        for j in range(i + 1, d):
            if u[i, j] == 1 or u[j, i] == 1:
                edges.append(f"{i}-{j}")
    return ", ".join(edges) if edges else "(none)"


def cpdag_to_string(directed: np.ndarray, undirected: np.ndarray) -> str:
    return (
        f"directed: {matrix_to_directed_edges(directed)}; "
        f"undirected: {matrix_to_undirected_edges(undirected)}"
    )


def flat_directed_columns(prefix: str, g: np.ndarray) -> Dict[str, Any]:
    g = remove_diag(g)
    return {f"{prefix}_{i}to{j}": float(g[i, j]) for i, j in EDGE_ORDER_3VAR}


def flat_undirected_columns(prefix: str, u: np.ndarray) -> Dict[str, Any]:
    u = remove_diag(u)
    return {
        f"{prefix}_{i}_{j}": float(1 if (u[i, j] == 1 or u[j, i] == 1) else 0)
        for i, j in PAIR_ORDER_3VAR
    }


# =============================================================================
# DAG -> CPDAG conversion, same logic as previous CPDAG benchmark script
# =============================================================================

def unshielded_colliders(dag: np.ndarray) -> Set[Tuple[int, int, int]]:
    """Return all unshielded colliders i -> k <- j, with i < j in tuple."""
    dag = remove_diag(dag).astype(int)
    d = dag.shape[0]
    colliders: Set[Tuple[int, int, int]] = set()
    for k in range(d):
        parents = [i for i in range(d) if dag[i, k] == 1]
        for a in range(len(parents)):
            for b in range(a + 1, len(parents)):
                i, j = parents[a], parents[b]
                if dag[i, j] == 0 and dag[j, i] == 0:
                    lo, hi = sorted((i, j))
                    colliders.add((lo, k, hi))
    return colliders


def enumerate_dags_with_skeleton(skel: np.ndarray) -> List[np.ndarray]:
    """Enumerate all acyclic orientations of a tiny skeleton."""
    skel = remove_diag(skel).astype(int)
    d = skel.shape[0]
    pairs = [(i, j) for i in range(d) for j in range(i + 1, d) if skel[i, j] == 1 or skel[j, i] == 1]
    dags: List[np.ndarray] = []
    for mask in range(1 << len(pairs)):
        adj = np.zeros((d, d), dtype=int)
        for bit_idx, (i, j) in enumerate(pairs):
            if (mask >> bit_idx) & 1:
                adj[i, j] = 1
            else:
                adj[j, i] = 1
        if is_acyclic(adj):
            dags.append(adj)
    return dags


def dag_to_cpdag_by_mec(dag: np.ndarray) -> Tuple[np.ndarray, np.ndarray, int]:
    """
    Convert a small DAG to CPDAG by enumerating its Markov equivalence class.

    Two DAGs are Markov equivalent iff they have the same skeleton and the same
    unshielded colliders. For 3 variables this enumeration is tiny and robust.

    Returns:
      directed, undirected, mec_size
    """
    dag = remove_diag(dag).astype(int)
    if not is_acyclic(dag):
        raise ValueError("Input graph is not a DAG; CPDAG is undefined.")

    skel = skeleton_from_dag_or_directed(dag)
    target_colliders = unshielded_colliders(dag)
    candidates = [cand for cand in enumerate_dags_with_skeleton(skel) if unshielded_colliders(cand) == target_colliders]
    if not candidates:
        raise RuntimeError("No Markov equivalent DAGs found. This should not happen.")

    d = dag.shape[0]
    directed = np.zeros((d, d), dtype=int)
    undirected = np.zeros((d, d), dtype=int)

    for i in range(d):
        for j in range(i + 1, d):
            if skel[i, j] == 0 and skel[j, i] == 0:
                continue
            orientations: List[Tuple[int, int]] = []
            for cand in candidates:
                if cand[i, j] == 1:
                    orientations.append((i, j))
                elif cand[j, i] == 1:
                    orientations.append((j, i))
                else:
                    raise RuntimeError("Candidate DAG does not match skeleton.")
            unique_orientations = set(orientations)
            if len(unique_orientations) == 1:
                a, b = next(iter(unique_orientations))
                directed[a, b] = 1
            else:
                undirected[i, j] = 1
                undirected[j, i] = 1

    np.fill_diagonal(directed, 0)
    np.fill_diagonal(undirected, 0)
    return directed, undirected, len(candidates)


# =============================================================================
# CPDAG metrics, same metric口径 as previous CPDAG benchmark script
# =============================================================================

def binary_stats(y_true: np.ndarray, y_pred: np.ndarray, prefix: str) -> Dict[str, Any]:
    y_true = np.asarray(y_true).astype(int).reshape(-1)
    y_pred = np.asarray(y_pred).astype(int).reshape(-1)
    tp = int(((y_true == 1) & (y_pred == 1)).sum())
    fp = int(((y_true == 0) & (y_pred == 1)).sum())
    fn = int(((y_true == 1) & (y_pred == 0)).sum())
    tn = int(((y_true == 0) & (y_pred == 0)).sum())
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    acc = (tp + tn) / (tp + fp + fn + tn) if (tp + fp + fn + tn) > 0 else np.nan
    return {
        f"{prefix}_tp": tp,
        f"{prefix}_fp": fp,
        f"{prefix}_fn": fn,
        f"{prefix}_tn": tn,
        f"{prefix}_precision": precision,
        f"{prefix}_recall": recall,
        f"{prefix}_f1": f1,
        f"{prefix}_accuracy": acc,
    }


def cpdag_pair_state(directed: np.ndarray, undirected: np.ndarray, i: int, j: int) -> str:
    directed = remove_diag(directed).astype(int)
    undirected = remove_diag(undirected).astype(int)
    has_undir = undirected[i, j] == 1 or undirected[j, i] == 1
    has_ij = directed[i, j] == 1
    has_ji = directed[j, i] == 1
    if has_undir and (has_ij or has_ji):
        return "invalid_mixed"
    if has_ij and has_ji:
        return "invalid_bidirected"
    if has_undir:
        return "undirected"
    if has_ij:
        return f"{i}->{j}"
    if has_ji:
        return f"{j}->{i}"
    return "none"


def cpdag_shd_pairwise(true_dir: np.ndarray, true_undir: np.ndarray, pred_dir: np.ndarray, pred_undir: np.ndarray) -> int:
    shd = 0
    d = true_dir.shape[0]
    for i in range(d):
        for j in range(i + 1, d):
            if cpdag_pair_state(true_dir, true_undir, i, j) != cpdag_pair_state(pred_dir, pred_undir, i, j):
                shd += 1
    return int(shd)


def compute_cpdag_metrics(true_dir: np.ndarray, true_undir: np.ndarray, pred_dir: np.ndarray, pred_undir: np.ndarray) -> Dict[str, Any]:
    true_dir = remove_diag(true_dir).astype(int)
    true_undir = remove_diag(true_undir).astype(int)
    pred_dir = remove_diag(pred_dir).astype(int)
    pred_undir = remove_diag(pred_undir).astype(int)

    row: Dict[str, Any] = {}
    row["cpdag_exact_match"] = bool(np.array_equal(true_dir, pred_dir) and np.array_equal(true_undir, pred_undir))
    row["cpdag_shd_pairwise"] = cpdag_shd_pairwise(true_dir, true_undir, pred_dir, pred_undir)

    true_skel = skeleton_from_cpdag(true_dir, true_undir)
    pred_skel = skeleton_from_cpdag(pred_dir, pred_undir)
    skel_true_vec = np.array([true_skel[i, j] for i, j in PAIR_ORDER_3VAR], dtype=int)
    skel_pred_vec = np.array([pred_skel[i, j] for i, j in PAIR_ORDER_3VAR], dtype=int)
    row["skeleton_exact_match"] = bool(np.array_equal(skel_true_vec, skel_pred_vec))
    row.update(binary_stats(skel_true_vec, skel_pred_vec, prefix="skeleton"))

    dir_true_vec = np.array([true_dir[i, j] for i, j in EDGE_ORDER_3VAR], dtype=int)
    dir_pred_vec = np.array([pred_dir[i, j] for i, j in EDGE_ORDER_3VAR], dtype=int)
    row["directed_exact_match"] = bool(np.array_equal(dir_true_vec, dir_pred_vec))
    row.update(binary_stats(dir_true_vec, dir_pred_vec, prefix="directed"))

    undir_true_vec = np.array([1 if (true_undir[i, j] == 1 or true_undir[j, i] == 1) else 0 for i, j in PAIR_ORDER_3VAR], dtype=int)
    undir_pred_vec = np.array([1 if (pred_undir[i, j] == 1 or pred_undir[j, i] == 1) else 0 for i, j in PAIR_ORDER_3VAR], dtype=int)
    row["undirected_exact_match"] = bool(np.array_equal(undir_true_vec, undir_pred_vec))
    row.update(binary_stats(undir_true_vec, undir_pred_vec, prefix="undirected"))
    return row


# =============================================================================
# CSNP model loading and inference
# =============================================================================

def load_csnp_model(csnp_work_dir: Path, run_name: str, model_checkpoint: str, device: str) -> Tuple[Any, Dict[str, Any], Path]:
    model_dir = csnp_work_dir / "experiments" / "causal_classification" / "models" / run_name
    config_path = model_dir / "config.json"
    model_path = model_dir / model_checkpoint

    if not config_path.exists():
        raise FileNotFoundError(f"Config not found: {config_path}")
    if not model_path.exists():
        raise FileNotFoundError(f"Model checkpoint not found: {model_path}")

    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    module = config.get("module", "probabilistic")
    model_kwargs = dict(
        d_model=config["d_model"],
        emb_depth=1,
        dim_feedforward=config["dim_feedforward"],
        nhead=config["nhead"],
        dropout=0.0,
        num_layers_encoder=config["num_layers_encoder"],
        num_layers_decoder=config["num_layers_decoder"],
        num_nodes=config["num_nodes"],
        n_perm_samples=config["n_perm_samples"],
        sinkhorn_iter=config["sinkhorn_iter"],
        use_positional_encoding=config["use_positional_encoding"],
        device=device,
        dtype=th.float32,
    )
    if module == "probabilistic":
        model = CausalProbabilisticDecoder(**model_kwargs).to(device)
    elif module == "probabilistic_ar":
        model = CausalProbabilisticARDecoder(
            **model_kwargs,
            num_topo_order_samples=config.get("num_topo_order_samples", 8),
            ar_hidden_dim=config.get("ar_hidden_dim", None),
        ).to(device)
    else:
        raise ValueError(
            f"Unsupported CSNP module in config: {module!r}. "
            "This evaluator currently supports 'probabilistic' and 'probabilistic_ar'."
        )

    try:
        state_dict = th.load(model_path, map_location=device, weights_only=True)
    except TypeError:
        # For older PyTorch versions without weights_only.
        state_dict = th.load(model_path, map_location=device)

    model.load_state_dict(state_dict)
    model.eval()
    return model, config, model_path


def run_csnp_cpdag(
    data: np.ndarray,
    model: Any,
    threshold: float,
    standardize: bool,
    num_perm_samples: int,
    device: str,
) -> Tuple[np.ndarray, np.ndarray, Dict[str, Any]]:
    """
    CSNP output -> mean probability matrix -> threshold DAG -> CPDAG.

    If thresholded output is cyclic/bidirected, strict CPDAG is undefined. We keep
    the thresholded directed graph as a proxy, set pred_cpdag_valid=False, and its
    exact match will normally be False.
    """
    x = maybe_standardize(data, standardize=standardize).astype(np.float32)
    inputs = th.tensor(x, dtype=th.float32).unsqueeze(0).to(device)

    old_n_perm_samples = getattr(model, "n_perm_samples", None)
    model.n_perm_samples = int(num_perm_samples)

    with th.no_grad():
        probs = model.forward(inputs, graph=None, is_training=False, mask=None)

    if old_n_perm_samples is not None:
        model.n_perm_samples = old_n_perm_samples

    probs_np = probs.detach().cpu().numpy()
    # Expected shape: [num_perm_samples, batch, d, d]
    if probs_np.ndim == 4:
        prob_graphs = probs_np[:, 0]
        mean_prob = prob_graphs.mean(axis=0)
    elif probs_np.ndim == 3:
        mean_prob = probs_np[0]
    elif probs_np.ndim == 2:
        mean_prob = probs_np
    else:
        raise RuntimeError(f"Unexpected CSNP probability output shape: {probs_np.shape}")

    mean_prob = np.asarray(mean_prob, dtype=np.float32)
    np.fill_diagonal(mean_prob, 0.0)

    pred_dag = (mean_prob > threshold).astype(int)
    np.fill_diagonal(pred_dag, 0)

    pred_is_dag = bool(is_acyclic(pred_dag))
    pred_cpdag_valid = False
    mec_size = np.nan
    if pred_is_dag:
        pred_dir, pred_undir, mec_size = dag_to_cpdag_by_mec(pred_dag)
        pred_cpdag_valid = True
    else:
        pred_dir = pred_dag.astype(int)
        pred_undir = np.zeros_like(pred_dir, dtype=int)

    extra: Dict[str, Any] = {
        "threshold": float(threshold),
        "standardized_input": bool(standardize),
        "csnp_num_perm_samples": int(num_perm_samples),
        "pred_is_dag": pred_is_dag,
        "pred_cpdag_valid": pred_cpdag_valid,
        "pred_mec_size": mec_size,
    }
    extra.update(flat_directed_columns("csnp_prob", mean_prob))
    extra.update(flat_directed_columns("csnp_threshold_dag", pred_dag))
    return pred_dir, pred_undir, extra


# =============================================================================
# Rows, file discovery, summary
# =============================================================================

def build_ok_row(
    *,
    graph_id: int,
    graph_name: str,
    graph_bitstring: str,
    num_samples: int,
    data_idx: int,
    h5_path: Path,
    method: str,
    variant: str,
    true_dag: np.ndarray,
    true_dir: np.ndarray,
    true_undir: np.ndarray,
    true_mec_size: int,
    pred_dir: np.ndarray,
    pred_undir: np.ndarray,
    extra: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    row: Dict[str, Any] = {
        "graph_id": graph_id,
        "graph_name": graph_name,
        "graph_bitstring": graph_bitstring,
        "num_samples": num_samples,
        "data_idx": data_idx,
        "h5_path": str(h5_path),
        "method": method,
        "variant": variant,
        "status": "ok",
        "true_dag_edges": matrix_to_directed_edges(true_dag),
        "true_cpdag_directed_edges": matrix_to_directed_edges(true_dir),
        "true_cpdag_undirected_edges": matrix_to_undirected_edges(true_undir),
        "pred_cpdag_directed_edges": matrix_to_directed_edges(pred_dir),
        "pred_cpdag_undirected_edges": matrix_to_undirected_edges(pred_undir),
        "true_cpdag": cpdag_to_string(true_dir, true_undir),
        "pred_cpdag": cpdag_to_string(pred_dir, pred_undir),
        "true_mec_size": true_mec_size,
    }
    if extra:
        row.update(extra)
    row.update(compute_cpdag_metrics(true_dir, true_undir, pred_dir, pred_undir))
    row.update(flat_directed_columns("true_dag", true_dag))
    row.update(flat_directed_columns("true_cpdag_dir", true_dir))
    row.update(flat_undirected_columns("true_cpdag_undir", true_undir))
    row.update(flat_directed_columns("pred_cpdag_dir", pred_dir))
    row.update(flat_undirected_columns("pred_cpdag_undir", pred_undir))
    return row


def build_error_row(
    *,
    graph_id: int,
    graph_name: str,
    graph_bitstring: str,
    num_samples: int,
    data_idx: int,
    h5_path: Path,
    method: str,
    variant: str,
    error: Exception,
) -> Dict[str, Any]:
    return {
        "graph_id": graph_id,
        "graph_name": graph_name,
        "graph_bitstring": graph_bitstring,
        "num_samples": num_samples,
        "data_idx": data_idx,
        "h5_path": str(h5_path),
        "method": method,
        "variant": variant,
        "status": "error",
        "error": repr(error),
    }


def find_h5_path(benchmark_root: Path, graph_id: int, num_samples: int, seed: int, num_datasets: int, mechanism: str, noise: str) -> Path:
    pattern = (
        benchmark_root
        / "3"
        / f"graph_{graph_id:02d}__*"
        / mechanism
        / noise
        / f"n_{num_samples}"
        / f"seed_{seed}"
        / f"benchmark_3var_numdatasets_{num_datasets}.h5"
    )
    matches = sorted(glob.glob(str(pattern)))
    if len(matches) != 1:
        raise FileNotFoundError(
            f"Expected exactly one h5 file for graph_id={graph_id}, n={num_samples}, "
            f"but found {len(matches)}. Pattern: {pattern}"
        )
    return Path(matches[0])


def attr_value(attrs: Dict[str, Any], key: str, default: Any) -> Any:
    v = attrs.get(key, default)
    if isinstance(v, bytes):
        return v.decode("utf-8")
    if isinstance(v, np.generic):
        return v.item()
    return v


def read_h5_metadata(h5_path: Path) -> Dict[str, Any]:
    with h5py.File(h5_path, "r") as f:
        attrs = dict(f.attrs)
        data_shape = tuple(f["data"].shape)
        label_shape = tuple(f["label"].shape)
    return {
        "graph_id": int(attr_value(attrs, "graph_id", -1)),
        "graph_name": str(attr_value(attrs, "graph_name", "unknown")),
        "graph_bitstring": str(attr_value(attrs, "graph_bitstring", "")),
        "num_samples": int(attr_value(attrs, "num_samples", data_shape[1])),
        "num_datasets": int(attr_value(attrs, "num_datasets", data_shape[0])),
        "data_shape": data_shape,
        "label_shape": label_shape,
    }


def make_summary(raw_df: pd.DataFrame) -> pd.DataFrame:
    if raw_df.empty:
        return pd.DataFrame()
    ok = raw_df[raw_df["status"] == "ok"].copy()
    if ok.empty:
        return pd.DataFrame()

    bool_cols = [
        "cpdag_exact_match",
        "skeleton_exact_match",
        "directed_exact_match",
        "undirected_exact_match",
        "pred_cpdag_valid",
        "pred_is_dag",
    ]
    for c in bool_cols:
        if c in ok.columns:
            ok[c] = ok[c].astype(float)

    group_cols = ["graph_id", "graph_name", "num_samples", "method", "variant"]
    agg_dict: Dict[str, Tuple[str, str]] = {
        "n_ok": ("status", "count"),
        "cpdag_exact_rate": ("cpdag_exact_match", "mean"),
        "mean_cpdag_shd_pairwise": ("cpdag_shd_pairwise", "mean"),
        "skeleton_exact_rate": ("skeleton_exact_match", "mean"),
        "mean_skeleton_f1": ("skeleton_f1", "mean"),
        "mean_skeleton_precision": ("skeleton_precision", "mean"),
        "mean_skeleton_recall": ("skeleton_recall", "mean"),
        "directed_exact_rate": ("directed_exact_match", "mean"),
        "mean_directed_f1": ("directed_f1", "mean"),
        "mean_directed_precision": ("directed_precision", "mean"),
        "mean_directed_recall": ("directed_recall", "mean"),
        "undirected_exact_rate": ("undirected_exact_match", "mean"),
        "mean_undirected_f1": ("undirected_f1", "mean"),
        "mean_undirected_precision": ("undirected_precision", "mean"),
        "mean_undirected_recall": ("undirected_recall", "mean"),
        "mean_skeleton_fp": ("skeleton_fp", "mean"),
        "mean_skeleton_fn": ("skeleton_fn", "mean"),
        "mean_directed_fp": ("directed_fp", "mean"),
        "mean_directed_fn": ("directed_fn", "mean"),
        "mean_undirected_fp": ("undirected_fp", "mean"),
        "mean_undirected_fn": ("undirected_fn", "mean"),
    }
    if "pred_cpdag_valid" in ok.columns:
        agg_dict["pred_cpdag_valid_rate"] = ("pred_cpdag_valid", "mean")
    if "pred_is_dag" in ok.columns:
        agg_dict["pred_is_dag_rate"] = ("pred_is_dag", "mean")

    summary = ok.groupby(group_cols, dropna=False).agg(**agg_dict).reset_index()

    errors = raw_df[raw_df["status"] == "error"]
    if not errors.empty:
        error_counts = errors.groupby(group_cols, dropna=False).size().reset_index(name="n_errors")
        summary = summary.merge(error_counts, on=group_cols, how="left")
        summary["n_errors"] = summary["n_errors"].fillna(0).astype(int)
    else:
        summary["n_errors"] = 0
    return summary


def concat_preserve_columns(dfs: Sequence[pd.DataFrame]) -> pd.DataFrame:
    non_empty = [df for df in dfs if df is not None and not df.empty]
    if not non_empty:
        return pd.DataFrame()
    return pd.concat(non_empty, ignore_index=True, sort=False)


# =============================================================================
# Main evaluation loop
# =============================================================================

def evaluate_csnp(args: argparse.Namespace) -> pd.DataFrame:
    csnp_work_dir = Path(args.csnp_work_dir).expanduser().resolve()
    benchmark_root = Path(args.benchmark_root).expanduser().resolve()

    if args.device == "auto":
        device = "cuda" if th.cuda.is_available() else "cpu"
    else:
        device = args.device

    print("=" * 100)
    print("Loading CSNP model")
    print("=" * 100)
    print(f"csnp_work_dir: {csnp_work_dir}")
    print(f"run_name:      {args.run_name}")
    print(f"checkpoint:    {args.model_checkpoint}")
    print(f"device:        {device}")

    model, config, model_path = load_csnp_model(
        csnp_work_dir=csnp_work_dir,
        run_name=args.run_name,
        model_checkpoint=args.model_checkpoint,
        device=device,
    )
    print(f"Loaded model: {model_path}")

    graph_ids = parse_int_list(args.graph_ids)
    sample_sizes = parse_int_list(args.sample_sizes)
    variant = f"{args.run_name}_{args.model_checkpoint}_meanprob_thr{args.threshold}_perm{args.num_perm_samples}"

    rows: List[Dict[str, Any]] = []
    start_time = time.time()

    for graph_id in graph_ids:
        for n in sample_sizes:
            try:
                h5_path = find_h5_path(
                    benchmark_root=benchmark_root,
                    graph_id=graph_id,
                    num_samples=n,
                    seed=args.seed,
                    num_datasets=args.num_datasets,
                    mechanism=args.mechanism,
                    noise=args.noise,
                )
            except FileNotFoundError as e:
                if args.skip_missing:
                    print(f"[SKIP] {e}")
                    continue
                raise

            meta = read_h5_metadata(h5_path)
            graph_name = meta["graph_name"]
            graph_bitstring = meta["graph_bitstring"]
            n_in_file = int(meta["num_datasets"])
            limit = n_in_file if args.max_datasets_per_file is None else min(n_in_file, args.max_datasets_per_file)

            print("-" * 100)
            print(f"Evaluating graph_id={graph_id}, graph_name={graph_name}, n={n}, datasets={limit}/{n_in_file}")
            print(f"h5: {h5_path}")

            with h5py.File(h5_path, "r") as f:
                for data_idx in range(limit):
                    data = np.asarray(f["data"][data_idx], dtype=np.float32)
                    true_dag = remove_diag(np.asarray(f["label"][data_idx], dtype=int))

                    try:
                        true_dir, true_undir, true_mec_size = dag_to_cpdag_by_mec(true_dag)
                        pred_dir, pred_undir, extra = run_csnp_cpdag(
                            data=data,
                            model=model,
                            threshold=args.threshold,
                            standardize=args.standardize_csnp,
                            num_perm_samples=args.num_perm_samples,
                            device=device,
                        )
                        extra["model_path"] = str(model_path)
                        rows.append(
                            build_ok_row(
                                graph_id=graph_id,
                                graph_name=graph_name,
                                graph_bitstring=graph_bitstring,
                                num_samples=n,
                                data_idx=data_idx,
                                h5_path=h5_path,
                                method="CSNP",
                                variant=variant,
                                true_dag=true_dag,
                                true_dir=true_dir,
                                true_undir=true_undir,
                                true_mec_size=true_mec_size,
                                pred_dir=pred_dir,
                                pred_undir=pred_undir,
                                extra=extra,
                            )
                        )
                    except Exception as e:
                        rows.append(
                            build_error_row(
                                graph_id=graph_id,
                                graph_name=graph_name,
                                graph_bitstring=graph_bitstring,
                                num_samples=n,
                                data_idx=data_idx,
                                h5_path=h5_path,
                                method="CSNP",
                                variant=variant,
                                error=e,
                            )
                        )

                    if args.progress_every > 0 and (data_idx + 1) % args.progress_every == 0:
                        print(f"  done {data_idx + 1}/{limit}")

    elapsed = time.time() - start_time
    print("=" * 100)
    print(f"Finished CSNP evaluation. rows={len(rows)}, elapsed={elapsed:.1f}s")
    return pd.DataFrame(rows)


# =============================================================================
# CLI
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate CSNP on generated 3-variable benchmark datasets using CPDAG metrics and merge with existing results."
    )

    parser.add_argument(
        "--csnp_work_dir",
        type=str,
        default="/home/rtyen/projects/CausalStructureNeuralProcess-main/ml2_meta_causal_discovery",
        help="Path to ml2_meta_causal_discovery directory in the CSNP project.",
    )
    parser.add_argument(
        "--benchmark_root",
        type=str,
        default="/home/rtyen/projects/avici-main/benchmark_data",
        help="Root directory containing generated benchmark_data.",
    )
    parser.add_argument(
        "--results_dir",
        type=str,
        default="/home/rtyen/projects/avici-main/benchmark_results_3var_cpdag",
        help="Directory containing previous raw_results_cpdag.csv and where new CSVs are written.",
    )

    parser.add_argument("--run_name", type=str, default="gp_3var_prob_rerun_100k")
    parser.add_argument("--model_checkpoint", type=str, default="model_8.pt")
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--threshold", type=float, default=0.5)
    parser.add_argument("--num_perm_samples", type=int, default=100)
    parser.add_argument(
        "--standardize_csnp",
        action="store_true",
        default=True,
        help="Standardize data before CSNP inference. Default: True, matching the old inspect_prediction_3var.py.",
    )
    parser.add_argument(
        "--no_standardize_csnp",
        action="store_false",
        dest="standardize_csnp",
        help="Disable standardization before CSNP inference.",
    )

    parser.add_argument("--graph_ids", type=str, default="0,1,15,16,17,24")
    parser.add_argument("--sample_sizes", type=str, default="50,100,200,500,1000,3000")
    parser.add_argument("--num_datasets", type=int, default=100)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--mechanism", type=str, default="linear")
    parser.add_argument("--noise", type=str, default="gaussian")
    parser.add_argument(
        "--max_datasets_per_file",
        type=int,
        default=None,
        help="Debug option: evaluate only first K datasets per h5 file.",
    )
    parser.add_argument("--skip_missing", action="store_true")
    parser.add_argument("--progress_every", type=int, default=20)

    parser.add_argument(
        "--existing_raw_name",
        type=str,
        default="raw_results_cpdag.csv",
        help="Previous raw CSV from AVICI/PC/GES benchmark.",
    )
    parser.add_argument("--csnp_raw_name", type=str, default="csnp_raw_results_cpdag.csv")
    parser.add_argument("--merged_raw_name", type=str, default="raw_results_cpdag_with_csnp.csv")
    parser.add_argument("--merged_summary_name", type=str, default="summary_results_cpdag_with_csnp.csv")
    parser.add_argument(
        "--no_merge",
        action="store_true",
        help="Only write CSNP raw results; do not merge with existing raw CSV.",
    )
    parser.add_argument(
        "--replace_original",
        action="store_true",
        help="After merging, also overwrite raw_results_cpdag.csv and summary_results_cpdag.csv with the merged versions.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()
    results_dir = Path(args.results_dir).expanduser().resolve()
    results_dir.mkdir(parents=True, exist_ok=True)

    csnp_raw_path = results_dir / args.csnp_raw_name
    existing_raw_path = results_dir / args.existing_raw_name
    merged_raw_path = results_dir / args.merged_raw_name
    merged_summary_path = results_dir / args.merged_summary_name

    csnp_df = evaluate_csnp(args)
    csnp_df.to_csv(csnp_raw_path, index=False)
    print(f"Wrote CSNP raw results: {csnp_raw_path}")

    if args.no_merge:
        print("--no_merge was set; stopping after CSNP raw output.")
        return

    if existing_raw_path.exists():
        old_df = pd.read_csv(existing_raw_path)
        print(f"Loaded existing raw results: {existing_raw_path}, rows={len(old_df)}")
    else:
        old_df = pd.DataFrame()
        print(f"Existing raw results not found: {existing_raw_path}. Merged file will contain only CSNP rows.")

    # Avoid duplicating this exact CSNP run if user reruns merge, while keeping
    # other CSNP variants such as older bak/current comparisons.
    if (
        not old_df.empty
        and "method" in old_df.columns
        and "variant" in old_df.columns
        and "method" in csnp_df.columns
        and "variant" in csnp_df.columns
    ):
        current_keys = set(zip(csnp_df["method"], csnp_df["variant"]))
        keep_old = ~old_df[["method", "variant"]].apply(tuple, axis=1).isin(current_keys)
        old_without_current_run = old_df[keep_old].copy()
    else:
        old_without_current_run = old_df

    merged_df = concat_preserve_columns([old_without_current_run, csnp_df])
    merged_df.to_csv(merged_raw_path, index=False)
    print(f"Wrote merged raw results: {merged_raw_path}, rows={len(merged_df)}")

    summary_df = make_summary(merged_df)
    summary_df.to_csv(merged_summary_path, index=False)
    print(f"Wrote merged summary results: {merged_summary_path}, rows={len(summary_df)}")

    if args.replace_original:
        raw_original = results_dir / "raw_results_cpdag.csv"
        summary_original = results_dir / "summary_results_cpdag.csv"
        merged_df.to_csv(raw_original, index=False)
        summary_df.to_csv(summary_original, index=False)
        print("Replaced original result CSVs:")
        print(f"  {raw_original}")
        print(f"  {summary_original}")

    print("Done.")


if __name__ == "__main__":
    main()
