#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sweep variable-node joint topo+skeleton checkpoints.

This evaluator is for mixed-node-count benchmark shards generated by
``generate_diverse_train_data.py``.  It avoids enumerating D! orders, so it can
evaluate D=3,...,10 checkpoints directly.
"""

from __future__ import annotations

import argparse
import glob
import json
import re
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import h5py
import numpy as np
import pandas as pd
import torch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from evaluate_topo_order_4var_summary import (  # noqa: E402
    encode_input,
    load_model,
    remove_diag,
    sample_topo_diffusion_orders_from_repr,
    summarize_orders,
    summarize_priority_order_match,
)
from test_code.evaluate_skeleton_L_summary import (  # noqa: E402
    average_precision_binary,
    roc_auc_score_binary,
)


SEM_NAMES = {
    0: "gp",
    1: "mlp",
    2: "linear",
}

ORDER_METRICS = [
    "topo_valid_rate",
    "mode_order_valid",
    "num_unique_orders",
    "mode_order_fraction",
    "avg_num_violations",
    "avg_violation_rate",
    "priority_exact_match",
    "priority_position_accuracy",
    "priority_pairwise_accuracy",
]
SKELETON_METRICS = [
    "skeleton_exact_match",
    "skeleton_shd",
    "skeleton_shd_norm",
    "skeleton_f1",
    "skeleton_auc",
    "skeleton_ap",
    "skeleton_brier",
]
PLOT_METRICS = [f"mean_{m}" for m in ORDER_METRICS + SKELETON_METRICS]


def parse_csv_list(value: str) -> List[str]:
    return [x.strip() for x in str(value).split(",") if x.strip()]


def parse_int_list(value: str) -> List[int]:
    return [int(x) for x in parse_csv_list(value)]


def parse_checkpoints(args: argparse.Namespace) -> List[str]:
    if args.checkpoints:
        checkpoints = parse_csv_list(args.checkpoints)
    else:
        checkpoints = [
            f"{args.checkpoint_prefix}{i}{args.checkpoint_suffix}"
            for i in range(args.checkpoint_start, args.checkpoint_end + 1)
        ]
    if not checkpoints:
        raise ValueError("No checkpoints selected.")
    return checkpoints


def checkpoint_index(checkpoint: str) -> int:
    match = re.search(r"(\d+)(?=\.pt$|$)", checkpoint)
    return int(match.group(1)) if match else -1


def discover_variable_h5_files(
    root: Path,
    split: str,
    node_counts: Sequence[int],
) -> Dict[int, List[Path]]:
    split_dir = root / split
    files_by_d: Dict[int, List[Path]] = {}
    for d in node_counts:
        files = sorted(split_dir.glob(f"d{d}_shard_*.hdf5"))
        files_by_d[d] = files
    return files_by_d


def metadata_sem_name(handle: h5py.File, index: int) -> str:
    if "metadata" not in handle:
        return "unknown"
    metadata = handle["metadata"][index]
    if "sem_type" not in metadata.dtype.names:
        return "unknown"
    sem_code = int(metadata["sem_type"])
    return SEM_NAMES.get(sem_code, f"sem_{sem_code}")


def maybe_limit_files(files: List[Path], limit: Optional[int]) -> List[Path]:
    if limit is None:
        return files
    return files[:limit]


def pair_order(num_nodes: int) -> List[Tuple[int, int]]:
    return [(i, j) for i in range(num_nodes) for j in range(i + 1, num_nodes)]


def skeleton_from_dag(dag: np.ndarray) -> np.ndarray:
    dag = remove_diag(dag).astype(int)
    skeleton = ((dag + dag.T) > 0).astype(int)
    np.fill_diagonal(skeleton, 0)
    return skeleton


def skeleton_metrics(
    true_dag: np.ndarray,
    skeleton_prob: np.ndarray,
    threshold: float,
) -> Dict[str, float]:
    true_skeleton = skeleton_from_dag(true_dag)
    pairs = pair_order(true_skeleton.shape[0])
    y_true = np.asarray([true_skeleton[i, j] for i, j in pairs], dtype=int)
    y_prob = np.asarray([skeleton_prob[i, j] for i, j in pairs], dtype=float)
    y_pred = (y_prob > threshold).astype(int)

    tp = int(((y_true == 1) & (y_pred == 1)).sum())
    fp = int(((y_true == 0) & (y_pred == 1)).sum())
    fn = int(((y_true == 1) & (y_pred == 0)).sum())
    denom = 2 * tp + fp + fn
    f1 = 1.0 if denom == 0 else 2 * tp / denom
    shd = float(np.abs(y_true - y_pred).sum())

    return {
        "skeleton_exact_match": float(np.array_equal(y_true, y_pred)),
        "skeleton_shd": shd,
        "skeleton_shd_norm": shd / max(len(pairs), 1),
        "skeleton_f1": float(f1),
        "skeleton_auc": roc_auc_score_binary(y_true, y_prob),
        "skeleton_ap": average_precision_binary(y_true, y_prob),
        "skeleton_brier": float(np.mean((y_prob - y_true) ** 2)),
    }


class RunningSummary:
    def __init__(self, group_cols: Sequence[str]) -> None:
        self.group_cols = list(group_cols)
        self.sums: Dict[Tuple[Any, ...], Dict[str, float]] = defaultdict(lambda: defaultdict(float))
        self.metric_counts: Dict[Tuple[Any, ...], Dict[str, int]] = defaultdict(lambda: defaultdict(int))
        self.counts: Dict[Tuple[Any, ...], int] = defaultdict(int)
        self.errors: Dict[Tuple[Any, ...], int] = defaultdict(int)

    def add_ok(self, group: Dict[str, Any], metrics: Dict[str, float]) -> None:
        key = tuple(group[c] for c in self.group_cols)
        self.counts[key] += 1
        for metric, value in metrics.items():
            if isinstance(value, (int, float, np.integer, np.floating)) and not pd.isna(value):
                self.sums[key][metric] += float(value)
                self.metric_counts[key][metric] += 1

    def add_error(self, group: Dict[str, Any]) -> None:
        key = tuple(group[c] for c in self.group_cols)
        self.errors[key] += 1

    def to_frame(self) -> pd.DataFrame:
        rows: List[Dict[str, Any]] = []
        keys = sorted(set(self.counts) | set(self.errors))
        for key in keys:
            row = {col: val for col, val in zip(self.group_cols, key)}
            row["n_ok"] = self.counts.get(key, 0)
            row["n_errors"] = self.errors.get(key, 0)
            for metric in ORDER_METRICS + SKELETON_METRICS:
                total = self.sums.get(key, {}).get(metric, 0.0)
                count = self.metric_counts.get(key, {}).get(metric, 0)
                row[f"mean_{metric}"] = total / count if count > 0 else np.nan
            rows.append(row)
        return pd.DataFrame(rows)


AGGREGATE_GROUP_COLS = [
    "benchmark", "node_count", "sample_size", "method", "checkpoint", "checkpoint_index", "mode"
]
BY_SEM_GROUP_COLS = [
    "benchmark", "node_count", "sample_size", "sem_type", "method", "checkpoint", "checkpoint_index", "mode"
]
DETAILED_GROUP_COLS = [
    "benchmark", "node_count", "sample_size", "sem_type", "file", "method", "checkpoint", "checkpoint_index", "mode"
]


def checkpoint_stem(checkpoint: str) -> str:
    return Path(checkpoint).stem


def checkpoint_output_paths(results_dir: Path, prefix: str, checkpoint: str) -> Tuple[Path, Path, Path]:
    ckpt_dir = results_dir / "checkpoints"
    stem = checkpoint_stem(checkpoint)
    return (
        ckpt_dir / f"{prefix}_{stem}_aggregate.csv",
        ckpt_dir / f"{prefix}_{stem}_by_sem.csv",
        ckpt_dir / f"{prefix}_{stem}_detailed.csv",
    )


def checkpoint_result_is_complete(aggregate_path: Path, by_sem_path: Path, detailed_path: Path) -> bool:
    if not (aggregate_path.exists() and by_sem_path.exists() and detailed_path.exists()):
        return False
    try:
        aggregate = pd.read_csv(aggregate_path)
        pd.read_csv(by_sem_path, nrows=1)
        pd.read_csv(detailed_path, nrows=1)
    except Exception:
        return False
    if aggregate.empty or "n_ok" not in aggregate.columns:
        return False
    return int(aggregate["n_ok"].sum()) > 0


def concat_csv_files(paths: Sequence[Path]) -> pd.DataFrame:
    frames = [pd.read_csv(path) for path in paths if path.exists()]
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def skeleton_prob_from_node_repr(model: Any, node_repr: torch.Tensor) -> np.ndarray:
    if not hasattr(model, "_skeleton_logits_from_node_repr"):
        raise ValueError("Model does not expose _skeleton_logits_from_node_repr.")
    with torch.no_grad():
        logits = model._skeleton_logits_from_node_repr(node_repr, mask=None)
        probs = torch.sigmoid(logits.float())[0]
        probs = (probs + probs.transpose(0, 1)) / 2.0
        probs.fill_diagonal_(0.0)
    return probs.detach().cpu().numpy().astype(float)


def standardize_full_dataset(data: np.ndarray, standardize: bool) -> np.ndarray:
    data = np.asarray(data, dtype=np.float32)
    if not standardize:
        return data
    return (data - data.mean(axis=0, keepdims=True)) / (data.std(axis=0, keepdims=True) + 1e-8)


def select_observations(
    data: np.ndarray,
    sample_size: int,
    seed: int,
) -> np.ndarray:
    if sample_size > data.shape[0]:
        raise ValueError(
            f"Requested sample_size={sample_size}, but dataset has only {data.shape[0]} rows."
        )
    if sample_size == data.shape[0]:
        return data
    rng = np.random.default_rng(seed)
    indices = rng.choice(data.shape[0], size=sample_size, replace=False)
    return data[indices]


def evaluate_dataset(
    *,
    model: Any,
    processed_data: np.ndarray,
    true_dag: np.ndarray,
    num_order_samples: int,
    device: str,
    standardize: bool,
    mode: str,
    threshold: float,
    evaluate_skeleton: bool,
) -> Dict[str, float]:
    # Match CausalClassifierTrainer: after collate/subsampling, inputs are
    # standardised again along the sample axis immediately before model(...).
    inputs = encode_input(processed_data, device=device, standardize=standardize)
    with torch.no_grad():
        node_repr = model._encode_raw_data(inputs, mask=None)

    sampled_orders, priorities = sample_topo_diffusion_orders_from_repr(
        model=model,
        node_repr=node_repr,
        num_order_samples=num_order_samples,
        deterministic=(mode == "deterministic"),
        beam=(mode == "beam"),
        return_priority=True,
    )
    metrics = summarize_orders(true_dag, sampled_orders)
    if priorities is not None:
        metrics.update(
            summarize_priority_order_match(
                true_dag,
                sampled_orders,
                priorities,
            )
        )

    if evaluate_skeleton:
        skeleton_prob = skeleton_prob_from_node_repr(model, node_repr)
        metrics.update(
            skeleton_metrics(
                true_dag=true_dag,
                skeleton_prob=skeleton_prob,
                threshold=threshold,
            )
        )
    return metrics


def evaluate(args: argparse.Namespace) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    device = "cuda" if args.device == "auto" and torch.cuda.is_available() else args.device
    if device == "auto":
        device = "cpu"

    benchmark_root = Path(args.benchmark_root).expanduser().resolve()
    models_root = Path(args.models_root).expanduser().resolve()
    node_counts = parse_int_list(args.node_counts)
    checkpoints = parse_checkpoints(args)
    modes = parse_csv_list(args.eval_modes)
    valid_modes = {"sample", "deterministic", "beam"}
    unknown_modes = set(modes) - valid_modes
    if unknown_modes:
        raise ValueError(f"Unknown eval modes: {sorted(unknown_modes)}")

    plot_groups = parse_csv_list(args.plot_groups)
    unknown_plot_groups = set(plot_groups) - {"topo", "skeleton"}
    if unknown_plot_groups:
        raise ValueError(f"Unknown plot groups: {sorted(unknown_plot_groups)}")
    evaluate_skeleton = "skeleton" in plot_groups

    sample_sizes = parse_int_list(args.sample_sizes)
    results_dir = Path(args.results_dir).expanduser().resolve()
    checkpoint_dir = results_dir / "checkpoints"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    files_by_d = discover_variable_h5_files(
        root=benchmark_root,
        split=args.split,
        node_counts=node_counts,
    )
    for d in node_counts:
        files_by_d[d] = maybe_limit_files(files_by_d[d], args.max_files_per_node)
        if not files_by_d[d]:
            if args.skip_missing:
                print(f"[SKIP] no hdf5 files for D={d}")
            else:
                raise FileNotFoundError(f"No hdf5 files found for D={d} under {benchmark_root / args.split}")

    aggregate_paths: List[Path] = []
    by_sem_paths: List[Path] = []
    detailed_paths: List[Path] = []

    print("=" * 100)
    print("Variable-node joint checkpoint sweep")
    print(f"benchmark_root:    {benchmark_root}")
    print(f"split:             {args.split}")
    print(f"node_counts:       {node_counts}")
    print(f"sample_sizes:      {sample_sizes}")
    print(f"checkpoints:       {checkpoints[0]} ... {checkpoints[-1]} ({len(checkpoints)})")
    print(f"eval_modes:        {modes}")
    print(f"num_order_samples: {args.num_order_samples}")
    print(f"device:            {device}")
    print("=" * 100)

    start = time.time()
    for checkpoint_idx, checkpoint in enumerate(checkpoints, start=1):
        aggregate_path, by_sem_path, detailed_path = checkpoint_output_paths(
            results_dir,
            args.summary_prefix,
            checkpoint,
        )
        if args.resume_existing and checkpoint_result_is_complete(aggregate_path, by_sem_path, detailed_path):
            print("=" * 100)
            print(f"[{checkpoint_idx}/{len(checkpoints)}] Skip completed checkpoint: {checkpoint}")
            aggregate_paths.append(aggregate_path)
            by_sem_paths.append(by_sem_path)
            detailed_paths.append(detailed_path)
            continue

        checkpoint_path = models_root / args.run_name / checkpoint
        if not checkpoint_path.exists():
            if args.skip_missing_checkpoints:
                print(f"[SKIP] missing checkpoint: {checkpoint_path}")
                continue
            raise FileNotFoundError(f"Missing checkpoint: {checkpoint_path}")

        print("=" * 100)
        print(f"[{checkpoint_idx}/{len(checkpoints)}] Loading {args.run_name}/{checkpoint}")
        model, _, loaded_path = load_model(
            models_root=models_root,
            run_name=args.run_name,
            checkpoint=checkpoint,
            source="current",
            device=device,
            bak_path=Path("ml2_meta_causal_discovery/models/causaltransformernp.py.mask_version.bak"),
        )
        print(f"loaded: {loaded_path}")
        ckpt_index = checkpoint_index(checkpoint)
        ckpt_aggregate = RunningSummary(AGGREGATE_GROUP_COLS)
        ckpt_by_sem = RunningSummary(BY_SEM_GROUP_COLS)
        ckpt_detailed = RunningSummary(DETAILED_GROUP_COLS)

        for mode in modes:
            for d in node_counts:
                files = files_by_d.get(d, [])
                if not files:
                    continue
                seen_for_d = 0
                print("-" * 100)
                print(f"checkpoint={checkpoint} mode={mode} D={d}: files={len(files)}")
                for file_idx, h5_path in enumerate(files, start=1):
                    with h5py.File(h5_path, "r") as handle:
                        data_arr = handle["data"]
                        label_arr = handle["label"]
                        file_count = int(data_arr.shape[0])
                        limit = file_count if args.max_datasets_per_file is None else min(file_count, args.max_datasets_per_file)
                        print(f"  [{file_idx}/{len(files)}] {h5_path.name} datasets={limit}/{file_count}")
                        for data_idx in range(limit):
                            if args.max_datasets_per_node is not None and seen_for_d >= args.max_datasets_per_node:
                                break
                            raw_data = np.asarray(data_arr[data_idx], dtype=np.float32)
                            normalized_data = standardize_full_dataset(
                                raw_data,
                                standardize=args.standardize,
                            )
                            true_dag = remove_diag(np.asarray(label_arr[data_idx], dtype=int))
                            sem_type = metadata_sem_name(handle, data_idx)
                            seen_for_d += 1
                            for sample_size in sample_sizes:
                                base_group = {
                                    "benchmark": args.benchmark_name,
                                    "node_count": d,
                                    "sample_size": sample_size,
                                    "method": args.method_name,
                                    "checkpoint": checkpoint,
                                    "checkpoint_index": ckpt_index,
                                    "mode": mode,
                                }
                                sem_group = dict(base_group)
                                sem_group["sem_type"] = sem_type
                                detail_group = dict(sem_group)
                                detail_group["file"] = h5_path.name

                                try:
                                    processed_data = select_observations(
                                        normalized_data,
                                        sample_size=sample_size,
                                        seed=(
                                            args.seed
                                            + d * 1000003
                                            + file_idx * 10007
                                            + data_idx * 101
                                            + sample_size
                                        ),
                                    )
                                    metrics = evaluate_dataset(
                                        model=model,
                                        processed_data=processed_data,
                                        true_dag=true_dag,
                                        num_order_samples=args.num_order_samples,
                                        device=device,
                                        standardize=args.standardize,
                                        mode=mode,
                                        threshold=args.threshold,
                                        evaluate_skeleton=evaluate_skeleton,
                                    )
                                    ckpt_aggregate.add_ok(base_group, metrics)
                                    ckpt_by_sem.add_ok(sem_group, metrics)
                                    ckpt_detailed.add_ok(detail_group, metrics)
                                except Exception as exc:
                                    ckpt_aggregate.add_error(base_group)
                                    ckpt_by_sem.add_error(sem_group)
                                    ckpt_detailed.add_error(detail_group)
                                    if args.print_errors:
                                        print(
                                            f"    [ERROR] D={d} n={sample_size} "
                                            f"file={h5_path.name} idx={data_idx}: {repr(exc)}"
                                        )
                    if args.max_datasets_per_node is not None and seen_for_d >= args.max_datasets_per_node:
                        break

        del model
        if device == "cuda":
            torch.cuda.empty_cache()

        ckpt_aggregate_frame = ckpt_aggregate.to_frame()
        ckpt_by_sem_frame = ckpt_by_sem.to_frame()
        ckpt_detailed_frame = ckpt_detailed.to_frame()
        aggregate_path.parent.mkdir(parents=True, exist_ok=True)
        ckpt_aggregate_frame.to_csv(aggregate_path, index=False)
        ckpt_by_sem_frame.to_csv(by_sem_path, index=False)
        ckpt_detailed_frame.to_csv(detailed_path, index=False)
        print(f"Wrote checkpoint aggregate: {aggregate_path}")
        print(f"Wrote checkpoint SEM:       {by_sem_path}")
        print(f"Wrote checkpoint detailed:  {detailed_path}")
        if (
            ckpt_aggregate_frame.empty
            or "n_ok" not in ckpt_aggregate_frame.columns
            or int(ckpt_aggregate_frame["n_ok"].sum()) == 0
        ):
            raise RuntimeError(
                f"All evaluations failed for {checkpoint}: checkpoint n_ok is 0. "
                "Re-run with --print_errors to inspect the first failures."
            )
        aggregate_paths.append(aggregate_path)
        by_sem_paths.append(by_sem_path)
        detailed_paths.append(detailed_path)

    print("=" * 100)
    print(f"Finished. elapsed={time.time() - start:.1f}s")
    return (
        concat_csv_files(aggregate_paths),
        concat_csv_files(by_sem_paths),
        concat_csv_files(detailed_paths),
    )


def save_metric_plots(
    frame: pd.DataFrame,
    plots_dir: Path,
    prefix: str,
    plot_groups: Sequence[str],
    plot_node_counts: Optional[Sequence[int]],
    plot_sample_sizes: Optional[Sequence[int]],
) -> List[Path]:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as exc:
        print(f"[WARN] matplotlib unavailable; skip plots: {repr(exc)}")
        return []

    plots_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    selected_metrics: List[str] = []
    if "topo" in plot_groups:
        selected_metrics.extend([f"mean_{metric}" for metric in ORDER_METRICS])
    if "skeleton" in plot_groups:
        selected_metrics.extend([f"mean_{metric}" for metric in SKELETON_METRICS])
    metric_cols = [
        col for col in selected_metrics
        if col in frame.columns and pd.api.types.is_numeric_dtype(frame[col])
    ]
    plot_frame = frame.copy()
    if plot_node_counts is not None:
        plot_frame = plot_frame[plot_frame["node_count"].isin(plot_node_counts)]
    if plot_sample_sizes is not None:
        plot_frame = plot_frame[plot_frame["sample_size"].isin(plot_sample_sizes)]

    for metric in metric_cols:
        group_name = "topo" if metric.replace("mean_", "") in ORDER_METRICS else "skeleton"
        metric_dir = plots_dir / group_name
        metric_dir.mkdir(parents=True, exist_ok=True)
        for sample_size in sorted(plot_frame["sample_size"].dropna().unique()):
            fig, ax = plt.subplots(figsize=(9.0, 5.5))
            plotted = False
            for mode in sorted(plot_frame["mode"].dropna().unique()):
                for d in sorted(plot_frame["node_count"].dropna().unique()):
                    sub = plot_frame[
                        (plot_frame["mode"] == mode)
                        & (plot_frame["node_count"] == d)
                        & (plot_frame["sample_size"] == sample_size)
                    ].sort_values("checkpoint_index")
                    sub = sub.dropna(subset=[metric])
                    if sub.empty:
                        continue
                    ax.plot(
                        sub["checkpoint_index"],
                        sub[metric],
                        marker="o",
                        linewidth=1.5,
                        label=f"{mode}, D={int(d)}",
                    )
                    plotted = True
            if not plotted:
                plt.close(fig)
                continue
            ax.set_xlabel("checkpoint index")
            ax.set_ylabel(metric)
            ax.set_title(f"{metric}, n={int(sample_size)}")
            ax.grid(True, alpha=0.3)
            ax.legend(fontsize=7, ncol=2)
            fig.tight_layout()
            out_path = metric_dir / f"{prefix}_{metric}_n{int(sample_size)}.png"
            fig.savefig(out_path, dpi=180)
            plt.close(fig)
            written.append(out_path)

        for d in sorted(plot_frame["node_count"].dropna().unique()):
            fig, ax = plt.subplots(figsize=(9.0, 5.5))
            plotted = False
            for mode in sorted(plot_frame["mode"].dropna().unique()):
                for sample_size in sorted(plot_frame["sample_size"].dropna().unique()):
                    sub = plot_frame[
                        (plot_frame["mode"] == mode)
                        & (plot_frame["node_count"] == d)
                        & (plot_frame["sample_size"] == sample_size)
                    ].sort_values("checkpoint_index")
                    sub = sub.dropna(subset=[metric])
                    if sub.empty:
                        continue
                    ax.plot(
                        sub["checkpoint_index"],
                        sub[metric],
                        marker="o",
                        linewidth=1.5,
                        label=f"{mode}, n={int(sample_size)}",
                    )
                    plotted = True
            if not plotted:
                plt.close(fig)
                continue
            ax.set_xlabel("checkpoint index")
            ax.set_ylabel(metric)
            ax.set_title(f"{metric}, D={int(d)}")
            ax.grid(True, alpha=0.3)
            ax.legend(fontsize=7, ncol=2)
            fig.tight_layout()
            out_path = metric_dir / f"{prefix}_{metric}_D{int(d)}.png"
            fig.savefig(out_path, dpi=180)
            plt.close(fig)
            written.append(out_path)
    return written


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate variable-node joint topo+skeleton checkpoint sweep.")
    parser.add_argument("--benchmark_root", type=str, required=True)
    parser.add_argument("--benchmark_name", type=str, default="id_no_gp_mlp08_linear02_n1000")
    parser.add_argument("--split", type=str, default="test")
    parser.add_argument("--node_counts", type=str, default="3,4,5,6,7,8,9,10")
    parser.add_argument("--sample_sizes", type=str, default="1000")
    parser.add_argument("--models_root", type=str, required=True)
    parser.add_argument("--run_name", type=str, required=True)
    parser.add_argument("--method_name", type=str, default="PriorityJointVar3to10")
    parser.add_argument("--checkpoints", type=str, default="")
    parser.add_argument("--checkpoint_start", type=int, default=70)
    parser.add_argument("--checkpoint_end", type=int, default=83)
    parser.add_argument("--checkpoint_prefix", type=str, default="model_")
    parser.add_argument("--checkpoint_suffix", type=str, default=".pt")
    parser.add_argument("--eval_modes", type=str, default="beam")
    parser.add_argument("--num_order_samples", type=int, default=200)
    parser.add_argument("--threshold", type=float, default=0.5)
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--standardize", action="store_true", default=True)
    parser.add_argument("--no_standardize", action="store_false", dest="standardize")
    parser.add_argument("--results_dir", type=str, required=True)
    parser.add_argument("--summary_prefix", type=str, default="variable_node_joint_sweep")
    parser.add_argument("--plot_groups", type=str, default="topo,skeleton")
    parser.add_argument("--plot_node_counts", type=str, default="")
    parser.add_argument("--plot_sample_sizes", type=str, default="")
    parser.add_argument("--max_files_per_node", type=int, default=None)
    parser.add_argument("--max_datasets_per_file", type=int, default=None)
    parser.add_argument("--max_datasets_per_node", type=int, default=None)
    parser.add_argument("--skip_missing", action="store_true")
    parser.add_argument("--skip_missing_checkpoints", action="store_true")
    parser.add_argument("--resume_existing", action="store_true")
    parser.add_argument("--print_errors", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    results_dir = Path(args.results_dir).expanduser().resolve()
    plots_dir = results_dir / "plots"
    results_dir.mkdir(parents=True, exist_ok=True)

    with open(results_dir / f"{args.summary_prefix}_args.json", "w", encoding="utf-8") as handle:
        json.dump(vars(args), handle, indent=2, ensure_ascii=False)

    aggregate, by_sem, detailed = evaluate(args)
    aggregate_path = results_dir / f"{args.summary_prefix}_aggregate.csv"
    by_sem_path = results_dir / f"{args.summary_prefix}_by_sem.csv"
    detailed_path = results_dir / f"{args.summary_prefix}_detailed.csv"
    aggregate.to_csv(aggregate_path, index=False)
    by_sem.to_csv(by_sem_path, index=False)
    detailed.to_csv(detailed_path, index=False)
    print(f"Wrote aggregate summary: {aggregate_path}")
    print(f"Wrote SEM summary:       {by_sem_path}")
    print(f"Wrote detailed summary:  {detailed_path}")
    if aggregate.empty or "n_ok" not in aggregate.columns or int(aggregate["n_ok"].sum()) == 0:
        raise RuntimeError(
            "All evaluations failed: aggregate n_ok is 0. "
            "Re-run with --print_errors to inspect the first failures."
        )

    plot_node_counts = parse_int_list(args.plot_node_counts) if args.plot_node_counts else None
    plot_sample_sizes = parse_int_list(args.plot_sample_sizes) if args.plot_sample_sizes else None
    plot_paths = save_metric_plots(
        aggregate,
        plots_dir,
        args.summary_prefix,
        plot_groups=parse_csv_list(args.plot_groups),
        plot_node_counts=plot_node_counts,
        plot_sample_sizes=plot_sample_sizes,
    )
    if plot_paths:
        print(f"Wrote {len(plot_paths)} plots under: {plots_dir}")


if __name__ == "__main__":
    main()
