#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Evaluate variable-node joint DAG predictions against PC/GES CPDAGs.

This is the variable-node counterpart of
``test_code/evaluate_joint_dag_cpdag_vs_traditional.py``.  It reads benchmark
shards generated by ``generate_diverse_train_data.py``:

    <benchmark_root>/<split>/d{D}_shard_*.hdf5

The learned joint topo+skeleton model is converted to a DAG by thresholding the
predicted skeleton and orienting every selected edge according to the sampled
topological order.  Both learned and traditional predictions are converted to
CPDAGs, then compared to the true CPDAG using only:

    cpdag_exact_match, cpdag_shd_pairwise
"""

from __future__ import annotations

import argparse
import glob
import re
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import h5py
import numpy as np
import pandas as pd
import torch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from evaluate_csnp_4var_gp_benchmark_summary import (  # noqa: E402
    causallearn_cpdag_to_arrays,
    compute_cpdag_metrics,
    cpdag_key,
    dag_to_cpdag_by_mec,
    most_common_item,
    remove_diag,
    run_ges_cpdag,
    run_pc_cpdag,
)
from evaluate_topo_order_4var_summary import (  # noqa: E402
    encode_input,
    load_model,
    sample_topo_diffusion_orders_from_repr,
)


KEEP_METRICS = ["cpdag_exact_match", "cpdag_shd_pairwise"]
SEM_NAMES = {0: "gp", 1: "mlp", 2: "linear"}


def parse_csv_list(value: str) -> List[str]:
    return [x.strip() for x in str(value).split(",") if x.strip()]


def parse_int_list(value: str) -> List[int]:
    return [int(x) for x in parse_csv_list(value)]


def discover_variable_h5_files(root: Path, split: str, node_counts: Sequence[int]) -> Dict[int, List[Path]]:
    split_dir = root / split
    return {d: sorted(split_dir.glob(f"d{d}_shard_*.hdf5")) for d in node_counts}


def metadata_sem_name(handle: h5py.File, index: int) -> str:
    if "metadata" not in handle:
        return "unknown"
    metadata = handle["metadata"][index]
    if "sem_type" not in metadata.dtype.names:
        return "unknown"
    return SEM_NAMES.get(int(metadata["sem_type"]), f"sem_{int(metadata['sem_type'])}")


def standardize_full_dataset(data: np.ndarray, standardize: bool) -> np.ndarray:
    data = np.asarray(data, dtype=np.float32)
    if not standardize:
        return data
    return (data - data.mean(axis=0, keepdims=True)) / (data.std(axis=0, keepdims=True) + 1e-8)


def select_observations(data: np.ndarray, sample_size: int, seed: int) -> np.ndarray:
    if sample_size > data.shape[0]:
        raise ValueError(f"sample_size={sample_size} > available rows={data.shape[0]}")
    if sample_size == data.shape[0]:
        return data
    rng = np.random.default_rng(seed)
    indices = rng.choice(data.shape[0], size=sample_size, replace=False)
    return data[indices]


def dag_to_cpdag_fast(dag: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Convert DAG to CPDAG without enumerating the Markov equivalence class."""
    dag = remove_diag(np.asarray(dag, dtype=int))
    try:
        from causallearn.graph.Dag import Dag
        from causallearn.graph.GraphNode import GraphNode
        from causallearn.utils.DAG2CPDAG import dag2cpdag

        nodes = [GraphNode(f"X{i}") for i in range(dag.shape[0])]
        graph = Dag(nodes)
        for i in range(dag.shape[0]):
            for j in range(dag.shape[1]):
                if dag[i, j] != 0:
                    graph.add_directed_edge(nodes[i], nodes[j])
        return causallearn_cpdag_to_arrays(dag2cpdag(graph))
    except Exception:
        if dag.shape[0] <= 5:
            directed, undirected, _ = dag_to_cpdag_by_mec(dag)
            return directed, undirected
        raise


def skeleton_prob_from_node_repr(model: Any, node_repr: torch.Tensor) -> np.ndarray:
    if not hasattr(model, "_skeleton_logits_from_node_repr"):
        raise ValueError("Joint CPDAG evaluation requires a model with _skeleton_logits_from_node_repr.")
    with torch.no_grad():
        logits = model._skeleton_logits_from_node_repr(node_repr, mask=None)
        probs = torch.sigmoid(logits.float())[0]
        probs = (probs + probs.transpose(0, 1)) / 2.0
        probs.fill_diagonal_(0.0)
    return probs.detach().cpu().numpy().astype(np.float64)


def orient_skeleton_by_order(skeleton_prob: np.ndarray, order: np.ndarray, threshold: float) -> np.ndarray:
    order = np.asarray(order, dtype=int)
    d = skeleton_prob.shape[0]
    if sorted(order.tolist()) != list(range(d)):
        raise ValueError(f"Invalid topological order: {order.tolist()}")

    position = np.empty(d, dtype=int)
    position[order] = np.arange(d)
    dag = np.zeros((d, d), dtype=int)
    for i in range(d):
        for j in range(i + 1, d):
            if float(skeleton_prob[i, j]) > threshold:
                if position[i] < position[j]:
                    dag[i, j] = 1
                else:
                    dag[j, i] = 1
    return dag


def orient_skeleton_by_layer_id(
    skeleton_prob: np.ndarray,
    layer_id: np.ndarray,
    threshold: float,
) -> np.ndarray:
    layer_id = np.asarray(layer_id, dtype=int)
    d = skeleton_prob.shape[0]
    dag = np.zeros((d, d), dtype=int)
    for i in range(d):
        for j in range(i + 1, d):
            if float(skeleton_prob[i, j]) > threshold:
                if layer_id[i] < layer_id[j]:
                    dag[i, j] = 1
                elif layer_id[j] < layer_id[i]:
                    dag[j, i] = 1
    return dag


def joint_predict_cpdag(
    model: Any,
    data: np.ndarray,
    *,
    device: str,
    standardize: bool,
    threshold: float,
    order_mode: str,
    num_order_samples: int,
) -> Tuple[np.ndarray, np.ndarray]:
    inputs = encode_input(data, device=device, standardize=standardize)
    with torch.no_grad():
        node_repr = model._encode_raw_data(inputs, mask=None)
    skeleton_prob = skeleton_prob_from_node_repr(model, node_repr)
    if hasattr(model, "_decode_source_layers_from_node_repr") and not hasattr(model, "reverse_model"):
        valid_nodes = torch.ones(
            node_repr.shape[:2],
            dtype=torch.bool,
            device=node_repr.device,
        )
        with torch.no_grad():
            layer_ids, _, _ = model._decode_source_layers_from_node_repr(
                node_repr,
                valid_nodes=valid_nodes,
            )
        pred_dag = orient_skeleton_by_layer_id(
            skeleton_prob,
            layer_ids[0].detach().cpu().numpy(),
            threshold,
        )
        return dag_to_cpdag_fast(pred_dag)

    orders = sample_topo_diffusion_orders_from_repr(
        model=model,
        node_repr=node_repr,
        num_order_samples=num_order_samples,
        deterministic=(order_mode == "deterministic"),
        beam=(order_mode == "beam"),
    )
    orders = np.asarray(orders, dtype=int).reshape(-1, skeleton_prob.shape[0])

    cpdag_counts: Dict[Any, int] = defaultdict(int)
    cpdag_by_key: Dict[Any, Tuple[np.ndarray, np.ndarray]] = {}
    for order in orders:
        pred_dag = orient_skeleton_by_order(skeleton_prob, order, threshold)
        pred_dir, pred_undir = dag_to_cpdag_fast(pred_dag)
        key = cpdag_key(pred_dir, pred_undir)
        cpdag_counts[key] += 1
        cpdag_by_key[key] = (pred_dir, pred_undir)
    return cpdag_by_key[most_common_item(cpdag_counts)]


class RunningSummary:
    def __init__(self, group_cols: Sequence[str]) -> None:
        self.group_cols = list(group_cols)
        self.sums: Dict[Tuple[Any, ...], Dict[str, float]] = defaultdict(lambda: defaultdict(float))
        self.counts: Dict[Tuple[Any, ...], int] = defaultdict(int)
        self.errors: Dict[Tuple[Any, ...], int] = defaultdict(int)

    def add_ok(self, group: Dict[str, Any], metrics: Dict[str, float]) -> None:
        key = tuple(group[c] for c in self.group_cols)
        self.counts[key] += 1
        for metric in KEEP_METRICS:
            value = metrics.get(metric)
            if isinstance(value, (int, float, np.integer, np.floating)) and not pd.isna(value):
                self.sums[key][metric] += float(value)

    def add_error(self, group: Dict[str, Any]) -> None:
        key = tuple(group[c] for c in self.group_cols)
        self.errors[key] += 1

    def to_frame(self) -> pd.DataFrame:
        rows: List[Dict[str, Any]] = []
        for key in sorted(set(self.counts) | set(self.errors)):
            n_ok = self.counts.get(key, 0)
            row = {col: value for col, value in zip(self.group_cols, key)}
            row["n_ok"] = n_ok
            row["n_errors"] = self.errors.get(key, 0)
            for metric in KEEP_METRICS:
                total = self.sums.get(key, {}).get(metric, np.nan)
                row[f"mean_{metric}"] = total / n_ok if n_ok > 0 else np.nan
            rows.append(row)
        return pd.DataFrame(rows)


def add_metrics(summary: RunningSummary, group: Dict[str, Any], true_dir: np.ndarray, true_undir: np.ndarray, pred_dir: np.ndarray, pred_undir: np.ndarray) -> None:
    summary.add_ok(group, compute_cpdag_metrics(true_dir, true_undir, pred_dir, pred_undir))


def evaluate(args: argparse.Namespace) -> pd.DataFrame:
    device = "cuda" if args.device == "auto" and torch.cuda.is_available() else args.device
    if device == "auto":
        device = "cpu"

    methods = set(parse_csv_list(args.methods))
    valid_methods = {"joint", "pc_fisherz", "pc_kci", "ges"}
    unknown = methods - valid_methods
    if unknown:
        raise ValueError(f"Unknown methods: {sorted(unknown)}. Use any of {sorted(valid_methods)}.")

    node_counts = parse_int_list(args.node_counts)
    sample_sizes = parse_int_list(args.sample_sizes)
    benchmark_root = Path(args.benchmark_root).expanduser().resolve()
    models_root = Path(args.models_root).expanduser().resolve()
    files_by_d = discover_variable_h5_files(benchmark_root, args.split, node_counts)
    for d in node_counts:
        files = files_by_d[d]
        if args.max_files_per_node is not None:
            files = files[: args.max_files_per_node]
            files_by_d[d] = files
        if not files:
            raise FileNotFoundError(f"No hdf5 files found for D={d} under {benchmark_root / args.split}")

    joint_model = None
    joint_variant = ""
    if "joint" in methods:
        print(f"Loading joint model: {args.joint_run_name}/{args.joint_checkpoint}")
        joint_model, config, loaded_path = load_model(
            models_root=models_root,
            run_name=args.joint_run_name,
            checkpoint=args.joint_checkpoint,
            source="current",
            device=device,
            bak_path=Path("ml2_meta_causal_discovery/models/causaltransformernp.py.mask_version.bak"),
        )
        has_order_sampler = (
            hasattr(joint_model, "reverse_model")
            or hasattr(joint_model, "_decode_source_layers_from_node_repr")
        )
        if not hasattr(joint_model, "_skeleton_logits_from_node_repr") or not has_order_sampler:
            raise ValueError(
                "The joint method requires a topo/source-layer model with a skeleton head "
                f"(loaded module={config.get('module')!r})."
            )
        joint_variant = (
            f"{args.joint_run_name}_{args.joint_checkpoint}_"
            f"{args.joint_order_mode}_orders{args.num_order_samples}_thr{args.threshold}"
        )
        print(f"  loaded: {loaded_path}")

    group_cols = ["benchmark", "node_count", "sample_size", "sem_type", "method", "variant"]
    summary = RunningSummary(group_cols)

    print("=" * 100)
    print("Variable-node joint DAG -> CPDAG vs traditional CPDAG evaluation")
    print(f"benchmark_root: {benchmark_root}")
    print(f"split:          {args.split}")
    print(f"node_counts:    {node_counts}")
    print(f"sample_sizes:   {sample_sizes}")
    print(f"methods:        {sorted(methods)}")
    print(f"device:         {device}")
    print("=" * 100)

    start = time.time()
    for d in node_counts:
        seen_for_d = 0
        for file_idx, h5_path in enumerate(files_by_d[d], start=1):
            with h5py.File(h5_path, "r") as handle:
                data_arr = handle["data"]
                label_arr = handle["label"]
                file_count = int(data_arr.shape[0])
                limit = file_count if args.max_datasets_per_file is None else min(file_count, args.max_datasets_per_file)
                print("-" * 100)
                print(f"D={d} [{file_idx}/{len(files_by_d[d])}] {h5_path.name} datasets={limit}/{file_count}")

                for data_idx in range(limit):
                    if args.max_datasets_per_node is not None and seen_for_d >= args.max_datasets_per_node:
                        break

                    raw_data = np.asarray(data_arr[data_idx], dtype=np.float32)
                    normalized_data = standardize_full_dataset(raw_data, standardize=args.standardize_dataset)
                    true_dag = remove_diag(np.asarray(label_arr[data_idx], dtype=int))
                    true_dir, true_undir = dag_to_cpdag_fast(true_dag)
                    sem_type = metadata_sem_name(handle, data_idx)
                    seen_for_d += 1

                    for sample_size in sample_sizes:
                        try:
                            data = select_observations(
                                normalized_data,
                                sample_size=sample_size,
                                seed=args.seed + d * 1000003 + file_idx * 10007 + data_idx * 101 + sample_size,
                            )
                        except Exception:
                            for method_name, variant in [
                                (args.joint_method_name, joint_variant),
                                ("PC-fisherz", f"alpha{args.pc_alpha}"),
                                ("PC-kci", f"alpha{args.pc_alpha}"),
                                ("GES-BIC", args.ges_score_func),
                            ]:
                                if method_name.startswith("PC-kci") and "pc_kci" not in methods:
                                    continue
                                group = {
                                    "benchmark": args.benchmark_name,
                                    "node_count": d,
                                    "sample_size": sample_size,
                                    "sem_type": sem_type,
                                    "method": method_name,
                                    "variant": variant,
                                }
                                summary.add_error(group)
                            continue

                        base = {
                            "benchmark": args.benchmark_name,
                            "node_count": d,
                            "sample_size": sample_size,
                            "sem_type": sem_type,
                        }

                        if "joint" in methods and joint_model is not None:
                            group = {**base, "method": args.joint_method_name, "variant": joint_variant}
                            try:
                                pred_dir, pred_undir = joint_predict_cpdag(
                                    joint_model,
                                    data,
                                    device=device,
                                    standardize=args.standardize_joint,
                                    threshold=args.threshold,
                                    order_mode=args.joint_order_mode,
                                    num_order_samples=args.num_order_samples,
                                )
                                add_metrics(summary, group, true_dir, true_undir, pred_dir, pred_undir)
                            except Exception as exc:
                                summary.add_error(group)
                                if args.print_errors:
                                    print(f"    [ERROR] joint D={d} n={sample_size} idx={data_idx}: {repr(exc)}")

                        if "pc_fisherz" in methods:
                            group = {**base, "method": "PC-fisherz", "variant": f"alpha{args.pc_alpha}"}
                            old_test = args.pc_test
                            args.pc_test = "fisherz"
                            try:
                                pred_dir, pred_undir = run_pc_cpdag(data, args)
                                add_metrics(summary, group, true_dir, true_undir, pred_dir, pred_undir)
                            except Exception as exc:
                                summary.add_error(group)
                                if args.print_errors:
                                    print(f"    [ERROR] PC-fisherz D={d} n={sample_size} idx={data_idx}: {repr(exc)}")
                            finally:
                                args.pc_test = old_test

                        if "pc_kci" in methods:
                            group = {**base, "method": "PC-kci", "variant": f"alpha{args.pc_alpha}"}
                            old_test = args.pc_test
                            args.pc_test = "kci"
                            try:
                                pred_dir, pred_undir = run_pc_cpdag(data, args)
                                add_metrics(summary, group, true_dir, true_undir, pred_dir, pred_undir)
                            except Exception as exc:
                                summary.add_error(group)
                                if args.print_errors:
                                    print(f"    [ERROR] PC-kci D={d} n={sample_size} idx={data_idx}: {repr(exc)}")
                            finally:
                                args.pc_test = old_test

                        if "ges" in methods:
                            group = {**base, "method": "GES-BIC", "variant": args.ges_score_func}
                            try:
                                pred_dir, pred_undir = run_ges_cpdag(data, args)
                                add_metrics(summary, group, true_dir, true_undir, pred_dir, pred_undir)
                            except Exception as exc:
                                summary.add_error(group)
                                if args.print_errors:
                                    print(f"    [ERROR] GES D={d} n={sample_size} idx={data_idx}: {repr(exc)}")

                    if args.progress_every > 0 and seen_for_d % args.progress_every == 0:
                        print(f"    done D={d}: {seen_for_d}")

            if args.max_datasets_per_node is not None and seen_for_d >= args.max_datasets_per_node:
                break

    print("=" * 100)
    print(f"Finished. elapsed={time.time() - start:.1f}s")
    return summary.to_frame()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate variable-node joint CPDAG metrics against PC/GES.")
    parser.add_argument("--benchmark_root", type=str, required=True)
    parser.add_argument("--split", type=str, default="test")
    parser.add_argument("--benchmark_name", type=str, default="")
    parser.add_argument("--node_counts", type=str, default="10")
    parser.add_argument("--sample_sizes", type=str, default="20,50,100,300,1000")
    parser.add_argument("--methods", type=str, default="joint,pc_fisherz,ges")
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])

    parser.add_argument("--models_root", type=str, required=True)
    parser.add_argument("--joint_run_name", type=str, required=True)
    parser.add_argument("--joint_checkpoint", type=str, required=True)
    parser.add_argument("--joint_method_name", type=str, default="JointTopoSkeleton")
    parser.add_argument("--joint_order_mode", type=str, default="beam", choices=["sample", "deterministic", "beam"])
    parser.add_argument("--num_order_samples", type=int, default=200)
    parser.add_argument("--threshold", type=float, default=0.5)

    parser.add_argument("--standardize_dataset", action="store_true", default=True)
    parser.add_argument("--no_standardize_dataset", action="store_false", dest="standardize_dataset")
    parser.add_argument("--standardize_joint", action="store_true", default=True)
    parser.add_argument("--no_standardize_joint", action="store_false", dest="standardize_joint")
    parser.add_argument("--standardize_traditional", action="store_true", default=True)
    parser.add_argument("--no_standardize_traditional", action="store_false", dest="standardize_traditional")

    parser.add_argument("--pc_alpha", type=float, default=0.05)
    parser.add_argument("--pc_test", type=str, default="fisherz", choices=["fisherz", "kci", "chisq", "gsq"])
    parser.add_argument("--pc_stable", action="store_true", default=True)
    parser.add_argument("--pc_uc_rule", type=int, default=0)
    parser.add_argument("--pc_uc_priority", type=int, default=2)
    parser.add_argument("--ges_score_func", type=str, default="local_score_BIC")

    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max_files_per_node", type=int, default=None)
    parser.add_argument("--max_datasets_per_file", type=int, default=None)
    parser.add_argument("--max_datasets_per_node", type=int, default=None)
    parser.add_argument("--progress_every", type=int, default=100)
    parser.add_argument("--print_errors", action="store_true")
    parser.add_argument("--results_dir", type=str, default="result/variable_joint_cpdag_vs_traditional")
    parser.add_argument("--summary_name", type=str, default="summary_variable_joint_cpdag_vs_traditional.csv")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.benchmark_name:
        args.benchmark_name = Path(args.benchmark_root).expanduser().resolve().name

    summary = evaluate(args)
    results_dir = Path(args.results_dir).expanduser().resolve()
    results_dir.mkdir(parents=True, exist_ok=True)
    summary_path = results_dir / args.summary_name
    summary.to_csv(summary_path, index=False)
    print(f"Wrote summary: {summary_path}")
    print(summary.to_string(index=False))


if __name__ == "__main__":
    main()
